name: "setup tools and caching for macOS workspace"
description: "setup tools and caching for macOS workspace"
inputs:
  gradle-cache-read-only:
    default: 'true'
    description: Updates gradle cache after actions if not read-only
  restore-workspace-cache:
    default: 'true'
    description: Whether to restore the workspace cache
  project:
    required: false
    description: single project to run

runs:
  using: "composite"
  steps:

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Gradle cache
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: ${{ inputs.gradle-cache-read-only }}
        gradle-home-cache-includes: |
          caches
          notifications

    - name: Make cache of workspace
      uses: actions/cache/restore@v4
      if: ${{ inputs.restore-workspace-cache != 'false' }}
      id: restore-build
      with:
        path: |
          ./*
          !/.gradle
        key: build-linux-${{ github.sha }}-${{ inputs.project }}
