name: Android tests
on:
  pull_request:
  push:
    branches: [ ci-example ]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=\"-Xmx8G -XX:MaxMetaspaceSize=512m -Dorg.gradle.daemon=false -Dkotlin.incremental=false\" -Dorg.gradle.daemon=false -Dkotlin.incremental=false -Dkotlin.daemon.jvm.options=-Xmx8G,-XX:MaxMetaspaceSize=512m,-Dorg.gradle.daemon=false,-Dkotlin.incremental=false"
  JAVA_OPTS: "-Xmx8G -XX:MaxMetaspaceSize=512m -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  example:
    runs-on:
      ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: build example
        run: ./gradlew android:assembleDebug
        working-directory: example

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Compile Android example
        run: ./gradlew testDebugUnitTest koverHtmlReport koverXmlReport
        working-directory: example

      - name: run Android unit tests
        run: ./gradlew testDebugUnitTest koverHtmlReport koverXmlReport
      - name: add coverage report to PR
        id: kover
        uses: mi-kas/kover-report@v1
        # this action fails if there is no report, unlike the above actions, so check if there are files
        if: ${{ always() && hashFiles(format('{0}/build/reports/kover/report.xml', github.workspace)) != '' }}
        with:
          path: ${{ github.workspace }}/build/reports/kover/report.xml
          token: ${{ secrets.CI_SPLENDO_PAT }}
          title: Code coverage
          update-comment: true
          coverage-counter-type: LINE
      - name: Upload Android test artifact
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: "Android Test Report HTML"
          path: "**/build/reports/tests/testDebugUnitTest"
      - name: Upload Coverage report
        uses: actions/upload-artifact@v4
        if: ${{ always() && hashFiles(format('{0}/build/reports/kover/html/index.html', github.workspace)) != '' }}
        with:
          name: "Android Test Report HTML"
          path: "**/build/reports/kover/html"
      - name: run apiCheck
        run: ./gradlew apiCheck
