name: Publish
on: push

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=\"-Xmx8g -XX:MaxMetaspaceSize=512m\" -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
  JAVA_OPTS: "-Xmx8g -XX:MaxMetaspaceSize=512m"

concurrency: publish-${{ github.ref_name }}

jobs:
  publish:
    env:
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
    runs-on: macos-12
    steps:
      - name: checkout
        uses: actions/checkout@v3

      # remove VM settings as defined for using the IDE
      - run: sed -i '' -e '/org.gradle.jvmargs/d' gradle.properties; cat gradle.properties

      - name : set up JDK 11
        uses : actions/setup-java@v3
        with :
          distribution : 'temurin'
          java-version : 11

      - name: Konan cache
        uses: actions/cache@v3
        id: konan-cache
        with:
          path: ~/.konan/*
          key: konan

      - run: ./gradlew publishAllPublicationsToSnapshotsRepository