name: Rerun failed emulator tests
permissions:
  contents: write
  
on:
  workflow_run:
    workflows: ["Android Emulator tests"]
    types:
      - completed

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.run_attempt < 2 }}
    env: 
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: gh run rerun ${{ github.event.workflow_run.id }} --failed
