name: 'Setup macOS workspace reusable workflow'

on:
  workflow_call:
    inputs:
      gradleTask:
        required: false
        type: string
      project:
        required: false
        type: string
      projectBlacklist:
        required: false
        type: string

    outputs:
      kotlinVersion:
        description: "kotlin version from libs.versions.toml"
        value: ${{ jobs.setup.outputs.kotlinVersion }}
      projects:
        description: "Gradle projects that do not dependent on another project or have other projects dependent on them"
        value: ${{ jobs.setup.outputs.projects }}
jobs:
  setup:

    runs-on: macos-15

    outputs:
      projects: ${{ steps.envFile.outputs.projects }}
      kotlinVersion: ${{ steps.kotlinVersion.outputs.value}}

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: read TOML version file
        id: kotlinVersion
        uses: SebRollen/toml-action@v1.2.0
        with:
          file: gradle/libs.versions.toml
          field: 'versions.kotlin'

      - name: setup tools and enable Gradle cache writing
        uses: ./.github/workflows/setup_tools_macos/
        with:
          gradle-cache-read-only: 'false'
          restore-workspace-cache: 'false'
          kotlinVersion: ${{ steps.kotlinVersion.outputs.value }}
          arch: ${{ runner.arch == 'X86' && 'x86' || runner.arch == 'X64' && 'x86_64' || runner.arch == 'ARM' && 'arm32' || 'arm64' }}
          project: ${{ inputs.project }}

      - name: generate file with projects for build matrix
        if: inputs.project == ''
        run: ./gradlew generateNonDependentProjectsFile -PgenerateNonDependentProjectsFile.blacklist=${{ inputs.projectBlacklist }}

      - name: generate file with single requested project for build matrix
        if: inputs.project != ''
        run: echo "projects=['${{ inputs.project }}']" > non_dependent_projects.properties

      - name: show projects for Matrix
        run: cat non_dependent_projects.properties

      - name: load projects for build matrix
        uses: cardinalby/export-env-action@v2
        id: envFile
        with:
          envFile: 'non_dependent_projects.properties'
          export: 'false'

      - name: run custom Gradle task for all projects
        if: inputs.project == ''
        run: ./gradlew ${{ inputs.gradleTask }}

      - name: run custom Gradle task for single project
        if: inputs.project != ''
        run: ./gradlew :${{ inputs.project }}:${{ inputs.gradleTask }}

      - name: Make cache of workspace
        uses: actions/cache/save@v4
        id: store-build
        with:
          path: |
            ./*
            !/.gradle
          key: build-iOS-${{ github.sha }}-${{ inputs.project }}
